# Use the Nginx image from Docker Hub
FROM nginx:1.19-alpine

# Remove default configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d
